services:
  psql_migrations_db:
    image: postgres
    container_name: ${POSTGRES_DATABASE_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - psql_migrations_db_data:/var/lib/postgresql/data
    networks:
      - psqldb-network

networks:
  psqldb-network:
    driver: bridge

volumes:
  psql_migrations_db_data: